// Code generated by go generate; DO NOT EDIT.
// This file is generated from masterdata_entities.yaml

package main

import (
	"encoding/json"
	"fmt"

	"github.com/yourusername/gosmartmillscale/desktop-app/internal/service"
)

// Master Data CRUD Operations - Auto-generated

// Produk Master Data

func (a *App) GetProdukPaginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.GetProdukPaginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated products: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) SearchProduk(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.SearchProduk(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search products: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}

// Unit Master Data

func (a *App) GetUnitPaginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.GetUnitPaginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated units: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) SearchUnit(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.SearchUnit(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search units: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}

// Supplier Master Data

func (a *App) GetSupplierPaginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.GetSupplierPaginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated suppliers: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) SearchSupplier(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.SearchSupplier(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search suppliers: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}

// Estate Master Data

func (a *App) GetEstatePaginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.GetEstatePaginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated estates: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) SearchEstate(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.SearchEstate(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search estates: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}

// Afdeling Master Data

func (a *App) GetAfdelingPaginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.GetAfdelingPaginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated afdelings: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) SearchAfdeling(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.SearchAfdeling(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search afdelings: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}

// Blok Master Data

func (a *App) GetBlokPaginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.GetBlokPaginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated bloks: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) SearchBlok(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.SearchBlok(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search bloks: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}
