package main

import (
	"bytes"
	"fmt"
	"os"
	"text/template"

	"gopkg.in/yaml.v3"
)

// Entity represents a master data entity configuration
type Entity struct {
	Name          string `yaml:"name"`
	Plural        string `yaml:"plural"`
	ServiceMethod string `yaml:"service_method"`
}

// Config represents the YAML configuration
type Config struct {
	Entities []Entity `yaml:"entities"`
}

const methodTemplate = `
// {{ .Name }} Master Data

func (a *App) Get{{ .Name }}Paginated(requestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var req service.PaginationRequest
	if err := json.Unmarshal([]byte(requestJSON), &req); err != nil {
		return "", fmt.Errorf("invalid request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.Get{{ .ServiceMethod }}Paginated(a.ctx, &req)
	if err != nil {
		return "", fmt.Errorf("failed to get paginated {{ .Plural }}: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal response: %w", err)
	}

	return string(data), nil
}

func (a *App) Search{{ .Name }}(searchRequestJSON string) (string, error) {
	if a.application == nil || a.application.Container == nil {
		return "", fmt.Errorf("application not initialized")
	}

	var filters service.SearchFilters
	if err := json.Unmarshal([]byte(searchRequestJSON), &filters); err != nil {
		return "", fmt.Errorf("invalid search request format: %w", err)
	}

	result, err := a.application.Container.PKSMasterService.Search{{ .ServiceMethod }}(a.ctx, &filters)
	if err != nil {
		return "", fmt.Errorf("failed to search {{ .Plural }}: %w", err)
	}

	data, err := json.Marshal(result)
	if err != nil {
		return "", fmt.Errorf("failed to marshal search response: %w", err)
	}

	return string(data), nil
}
`

const fileHeader = `// Code generated by go generate; DO NOT EDIT.
// This file is generated from masterdata_entities.yaml

package main

import (
	"encoding/json"
	"fmt"

	"github.com/yourusername/gosmartmillscale/desktop-app/internal/service"
)

// Master Data CRUD Operations - Auto-generated
`

func main() {
	// Read configuration
	configData, err := os.ReadFile("masterdata_entities.yaml")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading config: %v\n", err)
		os.Exit(1)
	}

	var config Config
	if err := yaml.Unmarshal(configData, &config); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing config: %v\n", err)
		os.Exit(1)
	}

	// Parse template
	tmpl, err := template.New("method").Parse(methodTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// Generate code
	var buf bytes.Buffer
	buf.WriteString(fileHeader)

	for _, entity := range config.Entities {
		if err := tmpl.Execute(&buf, entity); err != nil {
			fmt.Fprintf(os.Stderr, "Error executing template for %s: %v\n", entity.Name, err)
			os.Exit(1)
		}
	}

	// Write to file
	outputFile := "masterdata_generated.go"
	if err := os.WriteFile(outputFile, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Generated %s successfully!\n", outputFile)
	fmt.Printf("📊 Created %d entities with %d methods total\n", len(config.Entities), len(config.Entities)*2)
}
