// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDashboardWidget(arg1, arg2) {
  return window['go']['main']['App']['AddDashboardWidget'](arg1, arg2);
}

export function ChangePassword(arg1) {
  return window['go']['main']['App']['ChangePassword'](arg1);
}

export function CheckSession(arg1) {
  return window['go']['main']['App']['CheckSession'](arg1);
}

export function CheckSetupRequired() {
  return window['go']['main']['App']['CheckSetupRequired']();
}

export function CompleteTransaction(arg1, arg2) {
  return window['go']['main']['App']['CompleteTransaction'](arg1, arg2);
}

export function CreateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['CreateAPIKey'](arg1, arg2);
}

export function CreateAfdeling(arg1, arg2) {
  return window['go']['main']['App']['CreateAfdeling'](arg1, arg2);
}

export function CreateBlok(arg1, arg2) {
  return window['go']['main']['App']['CreateBlok'](arg1, arg2);
}

export function CreateEstate(arg1, arg2) {
  return window['go']['main']['App']['CreateEstate'](arg1, arg2);
}

export function CreateProduct(arg1, arg2) {
  return window['go']['main']['App']['CreateProduct'](arg1, arg2);
}

export function CreateSupplier(arg1, arg2) {
  return window['go']['main']['App']['CreateSupplier'](arg1, arg2);
}

export function CreateTimbang1(arg1, arg2) {
  return window['go']['main']['App']['CreateTimbang1'](arg1, arg2);
}

export function CreateUnit(arg1, arg2) {
  return window['go']['main']['App']['CreateUnit'](arg1, arg2);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function CreateWeighing(arg1, arg2) {
  return window['go']['main']['App']['CreateWeighing'](arg1, arg2);
}

export function DeactivateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['DeactivateAPIKey'](arg1, arg2);
}

export function DeleteAPIKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1, arg2);
}

export function DeleteAfdeling(arg1, arg2) {
  return window['go']['main']['App']['DeleteAfdeling'](arg1, arg2);
}

export function DeleteBlok(arg1, arg2) {
  return window['go']['main']['App']['DeleteBlok'](arg1, arg2);
}

export function DeleteEstate(arg1, arg2) {
  return window['go']['main']['App']['DeleteEstate'](arg1, arg2);
}

export function DeleteProduct(arg1, arg2) {
  return window['go']['main']['App']['DeleteProduct'](arg1, arg2);
}

export function DeleteSupplier(arg1, arg2) {
  return window['go']['main']['App']['DeleteSupplier'](arg1, arg2);
}

export function DeleteUnit(arg1, arg2) {
  return window['go']['main']['App']['DeleteUnit'](arg1, arg2);
}

export function DeleteUser(arg1, arg2) {
  return window['go']['main']['App']['DeleteUser'](arg1, arg2);
}

export function EmitSystemEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitSystemEvent'](arg1, arg2);
}

export function ExportPKSReportToCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportPKSReportToCSV'](arg1, arg2);
}

export function ExportPKSReportToExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportPKSReportToExcel'](arg1, arg2);
}

export function GeneratePKSReport(arg1, arg2) {
  return window['go']['main']['App']['GeneratePKSReport'](arg1, arg2);
}

export function GenerateTicketPreview(arg1) {
  return window['go']['main']['App']['GenerateTicketPreview'](arg1);
}

export function GetAPIKeys() {
  return window['go']['main']['App']['GetAPIKeys']();
}

export function GetAfdelingPaginated(arg1) {
  return window['go']['main']['App']['GetAfdelingPaginated'](arg1);
}

export function GetAfdelings(arg1) {
  return window['go']['main']['App']['GetAfdelings'](arg1);
}

export function GetAfdelingsByEstate(arg1, arg2) {
  return window['go']['main']['App']['GetAfdelingsByEstate'](arg1, arg2);
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetBlok(arg1) {
  return window['go']['main']['App']['GetBlok'](arg1);
}

export function GetBlokByAfdeling(arg1, arg2) {
  return window['go']['main']['App']['GetBlokByAfdeling'](arg1, arg2);
}

export function GetBlokPaginated(arg1) {
  return window['go']['main']['App']['GetBlokPaginated'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetCurrentWeight() {
  return window['go']['main']['App']['GetCurrentWeight']();
}

export function GetDashboardData(arg1) {
  return window['go']['main']['App']['GetDashboardData'](arg1);
}

export function GetEstatePaginated(arg1) {
  return window['go']['main']['App']['GetEstatePaginated'](arg1);
}

export function GetEstates(arg1) {
  return window['go']['main']['App']['GetEstates'](arg1);
}

export function GetMetricsData(arg1, arg2) {
  return window['go']['main']['App']['GetMetricsData'](arg1, arg2);
}

export function GetNextWeightEvent(arg1) {
  return window['go']['main']['App']['GetNextWeightEvent'](arg1);
}

export function GetPKSReportDatePresets(arg1) {
  return window['go']['main']['App']['GetPKSReportDatePresets'](arg1);
}

export function GetPKSReportFilters(arg1) {
  return window['go']['main']['App']['GetPKSReportFilters'](arg1);
}

export function GetPKSReportSummary(arg1, arg2) {
  return window['go']['main']['App']['GetPKSReportSummary'](arg1, arg2);
}

export function GetPKSStatistics(arg1) {
  return window['go']['main']['App']['GetPKSStatistics'](arg1);
}

export function GetPKSTimbanganByNoTransaksi(arg1) {
  return window['go']['main']['App']['GetPKSTimbanganByNoTransaksi'](arg1);
}

export function GetPasswordPolicy() {
  return window['go']['main']['App']['GetPasswordPolicy']();
}

export function GetPendingCompletion(arg1) {
  return window['go']['main']['App']['GetPendingCompletion'](arg1);
}

export function GetPendingTimbang2(arg1) {
  return window['go']['main']['App']['GetPendingTimbang2'](arg1);
}

export function GetPendingWeighings(arg1) {
  return window['go']['main']['App']['GetPendingWeighings'](arg1);
}

export function GetPrintStatistics(arg1) {
  return window['go']['main']['App']['GetPrintStatistics'](arg1);
}

export function GetProducts(arg1) {
  return window['go']['main']['App']['GetProducts'](arg1);
}

export function GetProdukPaginated(arg1) {
  return window['go']['main']['App']['GetProdukPaginated'](arg1);
}

export function GetRecentAuditLogs(arg1, arg2) {
  return window['go']['main']['App']['GetRecentAuditLogs'](arg1, arg2);
}

export function GetRecentWeighings(arg1) {
  return window['go']['main']['App']['GetRecentWeighings'](arg1);
}

export function GetServiceHealth(arg1) {
  return window['go']['main']['App']['GetServiceHealth'](arg1);
}

export function GetSupplierPaginated(arg1) {
  return window['go']['main']['App']['GetSupplierPaginated'](arg1);
}

export function GetSuppliers(arg1) {
  return window['go']['main']['App']['GetSuppliers'](arg1);
}

export function GetSyncConfig() {
  return window['go']['main']['App']['GetSyncConfig']();
}

export function GetSyncHistory(arg1) {
  return window['go']['main']['App']['GetSyncHistory'](arg1);
}

export function GetSyncMetrics() {
  return window['go']['main']['App']['GetSyncMetrics']();
}

export function GetSyncQueue(arg1, arg2) {
  return window['go']['main']['App']['GetSyncQueue'](arg1, arg2);
}

export function GetSyncStatistics() {
  return window['go']['main']['App']['GetSyncStatistics']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetSyncStatusTyped() {
  return window['go']['main']['App']['GetSyncStatusTyped']();
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function GetTicketByNumber(arg1) {
  return window['go']['main']['App']['GetTicketByNumber'](arg1);
}

export function GetTicketHistory(arg1, arg2) {
  return window['go']['main']['App']['GetTicketHistory'](arg1, arg2);
}

export function GetUnitPaginated(arg1) {
  return window['go']['main']['App']['GetUnitPaginated'](arg1);
}

export function GetUnits(arg1) {
  return window['go']['main']['App']['GetUnits'](arg1);
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function GetUserByUsername(arg1) {
  return window['go']['main']['App']['GetUserByUsername'](arg1);
}

export function GetUserStatistics() {
  return window['go']['main']['App']['GetUserStatistics']();
}

export function GetWeighingByID(arg1) {
  return window['go']['main']['App']['GetWeighingByID'](arg1);
}

export function GetWeighingStatistics() {
  return window['go']['main']['App']['GetWeighingStatistics']();
}

export function GetWeightHistory(arg1, arg2) {
  return window['go']['main']['App']['GetWeightHistory'](arg1, arg2);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function InitializeAuthenticatedServices(arg1) {
  return window['go']['main']['App']['InitializeAuthenticatedServices'](arg1);
}

export function IsServicesReady() {
  return window['go']['main']['App']['IsServicesReady']();
}

export function IsWeightMonitoringActive() {
  return window['go']['main']['App']['IsWeightMonitoringActive']();
}

export function IsWeightScaleConnected() {
  return window['go']['main']['App']['IsWeightScaleConnected']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function MarkWeighingAsSynced(arg1) {
  return window['go']['main']['App']['MarkWeighingAsSynced'](arg1);
}

export function PrintTicket(arg1) {
  return window['go']['main']['App']['PrintTicket'](arg1);
}

export function QueueForSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueueForSync'](arg1, arg2, arg3);
}

export function ReactivateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ReactivateAPIKey'](arg1, arg2);
}

export function RefreshDashboard(arg1) {
  return window['go']['main']['App']['RefreshDashboard'](arg1);
}

export function RefreshSession(arg1) {
  return window['go']['main']['App']['RefreshSession'](arg1);
}

export function RemoveDashboardWidget(arg1, arg2) {
  return window['go']['main']['App']['RemoveDashboardWidget'](arg1, arg2);
}

export function RequireAuthenticatedServices() {
  return window['go']['main']['App']['RequireAuthenticatedServices']();
}

export function ResetAuthenticatedServices() {
  return window['go']['main']['App']['ResetAuthenticatedServices']();
}

export function ResetPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetPassword'](arg1, arg2);
}

export function RetryFailedSyncs() {
  return window['go']['main']['App']['RetryFailedSyncs']();
}

export function SearchAfdeling(arg1) {
  return window['go']['main']['App']['SearchAfdeling'](arg1);
}

export function SearchBlok(arg1) {
  return window['go']['main']['App']['SearchBlok'](arg1);
}

export function SearchEstate(arg1) {
  return window['go']['main']['App']['SearchEstate'](arg1);
}

export function SearchPKSTimbangans(arg1) {
  return window['go']['main']['App']['SearchPKSTimbangans'](arg1);
}

export function SearchProduk(arg1) {
  return window['go']['main']['App']['SearchProduk'](arg1);
}

export function SearchSupplier(arg1) {
  return window['go']['main']['App']['SearchSupplier'](arg1);
}

export function SearchUnit(arg1) {
  return window['go']['main']['App']['SearchUnit'](arg1);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SearchWeighings(arg1) {
  return window['go']['main']['App']['SearchWeighings'](arg1);
}

export function StartWeightMonitoring() {
  return window['go']['main']['App']['StartWeightMonitoring']();
}

export function StartWeightMonitoringTyped() {
  return window['go']['main']['App']['StartWeightMonitoringTyped']();
}

export function StopWeightMonitoring() {
  return window['go']['main']['App']['StopWeightMonitoring']();
}

export function StopWeightMonitoringTyped() {
  return window['go']['main']['App']['StopWeightMonitoringTyped']();
}

export function SubscribeToWeightEvents(arg1) {
  return window['go']['main']['App']['SubscribeToWeightEvents'](arg1);
}

export function TestCOMPortConnection(arg1) {
  return window['go']['main']['App']['TestCOMPortConnection'](arg1);
}

export function TriggerManualSync(arg1) {
  return window['go']['main']['App']['TriggerManualSync'](arg1);
}

export function UnsubscribeFromWeightEvents(arg1) {
  return window['go']['main']['App']['UnsubscribeFromWeightEvents'](arg1);
}

export function UpdateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['UpdateAPIKey'](arg1, arg2);
}

export function UpdateAfdeling(arg1, arg2) {
  return window['go']['main']['App']['UpdateAfdeling'](arg1, arg2);
}

export function UpdateBlok(arg1, arg2) {
  return window['go']['main']['App']['UpdateBlok'](arg1, arg2);
}

export function UpdateDashboardData(arg1, arg2) {
  return window['go']['main']['App']['UpdateDashboardData'](arg1, arg2);
}

export function UpdateDashboardLayout(arg1, arg2) {
  return window['go']['main']['App']['UpdateDashboardLayout'](arg1, arg2);
}

export function UpdateDashboardWidget(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDashboardWidget'](arg1, arg2, arg3);
}

export function UpdateEstate(arg1, arg2) {
  return window['go']['main']['App']['UpdateEstate'](arg1, arg2);
}

export function UpdateProduct(arg1, arg2) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2);
}

export function UpdateSupplier(arg1, arg2) {
  return window['go']['main']['App']['UpdateSupplier'](arg1, arg2);
}

export function UpdateSyncConfig(arg1) {
  return window['go']['main']['App']['UpdateSyncConfig'](arg1);
}

export function UpdateTimbang2(arg1, arg2) {
  return window['go']['main']['App']['UpdateTimbang2'](arg1, arg2);
}

export function UpdateUnit(arg1, arg2) {
  return window['go']['main']['App']['UpdateUnit'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}

export function UpdateWeighing(arg1, arg2) {
  return window['go']['main']['App']['UpdateWeighing'](arg1, arg2);
}

export function ValidatePKSReportRequest(arg1, arg2) {
  return window['go']['main']['App']['ValidatePKSReportRequest'](arg1, arg2);
}

export function ValidateWeighing(arg1) {
  return window['go']['main']['App']['ValidateWeighing'](arg1);
}
