// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {service} from '../models';
import {main} from '../models';

export function AddDashboardWidget(arg1:string,arg2:string):Promise<string>;

export function ChangePassword(arg1:string):Promise<string>;

export function CheckSession(arg1:string):Promise<string>;

export function CheckSetupRequired():Promise<string>;

export function CompleteTransaction(arg1:string,arg2:string):Promise<string>;

export function CreateAPIKey(arg1:string,arg2:string):Promise<string>;

export function CreateAfdeling(arg1:string,arg2:string):Promise<string>;

export function CreateBlok(arg1:string,arg2:string):Promise<string>;

export function CreateEstate(arg1:string,arg2:string):Promise<string>;

export function CreateProduct(arg1:string,arg2:string):Promise<string>;

export function CreateSupplier(arg1:string,arg2:string):Promise<string>;

export function CreateTimbang1(arg1:string,arg2:string):Promise<string>;

export function CreateUnit(arg1:string,arg2:string):Promise<string>;

export function CreateUser(arg1:string,arg2:string):Promise<string>;

export function CreateWeighing(arg1:string,arg2:string):Promise<string>;

export function DeactivateAPIKey(arg1:string,arg2:string):Promise<string>;

export function DeleteAPIKey(arg1:string,arg2:string):Promise<string>;

export function DeleteAfdeling(arg1:string,arg2:string):Promise<void>;

export function DeleteBlok(arg1:string,arg2:string):Promise<void>;

export function DeleteEstate(arg1:string,arg2:string):Promise<void>;

export function DeleteProduct(arg1:string,arg2:string):Promise<void>;

export function DeleteSupplier(arg1:string,arg2:string):Promise<void>;

export function DeleteUnit(arg1:string,arg2:string):Promise<void>;

export function DeleteUser(arg1:string,arg2:string):Promise<string>;

export function EmitSystemEvent(arg1:string,arg2:any):Promise<void>;

export function ExportPKSReportToCSV(arg1:context.Context,arg2:service.ReportRequest):Promise<string>;

export function ExportPKSReportToExcel(arg1:context.Context,arg2:service.ReportRequest):Promise<Array<number>>;

export function GeneratePKSReport(arg1:context.Context,arg2:service.ReportRequest):Promise<service.ReportData>;

export function GenerateTicketPreview(arg1:string):Promise<string>;

export function GetAPIKeys():Promise<string>;

export function GetAfdelingPaginated(arg1:string):Promise<string>;

export function GetAfdelings(arg1:boolean):Promise<string>;

export function GetAfdelingsByEstate(arg1:string,arg2:boolean):Promise<string>;

export function GetAllUsers():Promise<string>;

export function GetBlok(arg1:boolean):Promise<string>;

export function GetBlokByAfdeling(arg1:string,arg2:boolean):Promise<string>;

export function GetBlokPaginated(arg1:string):Promise<string>;

export function GetCurrentUser():Promise<string>;

export function GetCurrentWeight():Promise<string>;

export function GetDashboardData(arg1:string):Promise<string>;

export function GetEstatePaginated(arg1:string):Promise<string>;

export function GetEstates(arg1:boolean):Promise<string>;

export function GetMetricsData(arg1:string,arg2:string):Promise<string>;

export function GetNextWeightEvent(arg1:string):Promise<string>;

export function GetPKSReportDatePresets(arg1:context.Context):Promise<Array<service.DatePreset>>;

export function GetPKSReportFilters(arg1:context.Context):Promise<service.ReportFilterOptions>;

export function GetPKSReportSummary(arg1:context.Context,arg2:service.ReportRequest):Promise<service.ReportSummary>;

export function GetPKSStatistics(arg1:number):Promise<string>;

export function GetPKSTimbanganByNoTransaksi(arg1:string):Promise<string>;

export function GetPasswordPolicy():Promise<string>;

export function GetPendingCompletion(arg1:number):Promise<string>;

export function GetPendingTimbang2(arg1:number):Promise<string>;

export function GetPendingWeighings(arg1:number):Promise<string>;

export function GetPrintStatistics(arg1:number):Promise<string>;

export function GetProducts(arg1:boolean):Promise<string>;

export function GetProdukPaginated(arg1:string):Promise<string>;

export function GetRecentAuditLogs(arg1:number,arg2:number):Promise<string>;

export function GetRecentWeighings(arg1:number):Promise<string>;

export function GetServiceHealth(arg1:string):Promise<string>;

export function GetSupplierPaginated(arg1:string):Promise<string>;

export function GetSuppliers(arg1:boolean):Promise<string>;

export function GetSyncConfig():Promise<string>;

export function GetSyncHistory(arg1:number):Promise<string>;

export function GetSyncMetrics():Promise<string>;

export function GetSyncQueue(arg1:string,arg2:number):Promise<string>;

export function GetSyncStatistics():Promise<string>;

export function GetSyncStatus():Promise<string>;

export function GetSyncStatusTyped():Promise<main.SyncStatusResponse>;

export function GetSystemHealth():Promise<string>;

export function GetTicketByNumber(arg1:string):Promise<string>;

export function GetTicketHistory(arg1:number,arg2:number):Promise<string>;

export function GetUnitPaginated(arg1:string):Promise<string>;

export function GetUnits(arg1:boolean):Promise<string>;

export function GetUserByID(arg1:string):Promise<string>;

export function GetUserByUsername(arg1:string):Promise<string>;

export function GetUserStatistics():Promise<string>;

export function GetWeighingByID(arg1:string):Promise<string>;

export function GetWeighingStatistics():Promise<string>;

export function GetWeightHistory(arg1:number,arg2:number):Promise<string>;

export function HealthCheck():Promise<string>;

export function InitializeAuthenticatedServices(arg1:string):Promise<void>;

export function IsServicesReady():Promise<boolean>;

export function IsWeightMonitoringActive():Promise<string>;

export function IsWeightScaleConnected():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout(arg1:string):Promise<void>;

export function MarkWeighingAsSynced(arg1:string):Promise<void>;

export function PrintTicket(arg1:string):Promise<string>;

export function QueueForSync(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReactivateAPIKey(arg1:string,arg2:string):Promise<string>;

export function RefreshDashboard(arg1:string):Promise<string>;

export function RefreshSession(arg1:string):Promise<string>;

export function RemoveDashboardWidget(arg1:string,arg2:string):Promise<string>;

export function RequireAuthenticatedServices():Promise<void>;

export function ResetAuthenticatedServices():Promise<void>;

export function ResetPassword(arg1:string,arg2:string):Promise<string>;

export function RetryFailedSyncs():Promise<string>;

export function SearchAfdeling(arg1:string):Promise<string>;

export function SearchBlok(arg1:string):Promise<string>;

export function SearchEstate(arg1:string):Promise<string>;

export function SearchPKSTimbangans(arg1:string):Promise<string>;

export function SearchProduk(arg1:string):Promise<string>;

export function SearchSupplier(arg1:string):Promise<string>;

export function SearchUnit(arg1:string):Promise<string>;

export function SearchUsers(arg1:string):Promise<string>;

export function SearchWeighings(arg1:string):Promise<string>;

export function StartWeightMonitoring():Promise<void>;

export function StartWeightMonitoringTyped():Promise<void>;

export function StopWeightMonitoring():Promise<void>;

export function StopWeightMonitoringTyped():Promise<void>;

export function SubscribeToWeightEvents(arg1:string):Promise<string>;

export function TestCOMPortConnection(arg1:string):Promise<string>;

export function TriggerManualSync(arg1:string):Promise<string>;

export function UnsubscribeFromWeightEvents(arg1:string):Promise<string>;

export function UpdateAPIKey(arg1:string,arg2:string):Promise<string>;

export function UpdateAfdeling(arg1:string,arg2:string):Promise<string>;

export function UpdateBlok(arg1:string,arg2:string):Promise<string>;

export function UpdateDashboardData(arg1:string,arg2:string):Promise<string>;

export function UpdateDashboardLayout(arg1:string,arg2:string):Promise<string>;

export function UpdateDashboardWidget(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UpdateEstate(arg1:string,arg2:string):Promise<string>;

export function UpdateProduct(arg1:string,arg2:string):Promise<string>;

export function UpdateSupplier(arg1:string,arg2:string):Promise<string>;

export function UpdateSyncConfig(arg1:string):Promise<void>;

export function UpdateTimbang2(arg1:string,arg2:string):Promise<string>;

export function UpdateUnit(arg1:string,arg2:string):Promise<string>;

export function UpdateUser(arg1:string,arg2:string):Promise<string>;

export function UpdateWeighing(arg1:string,arg2:string):Promise<string>;

export function ValidatePKSReportRequest(arg1:context.Context,arg2:service.ReportRequest):Promise<service.ValidationResult>;

export function ValidateWeighing(arg1:string):Promise<string>;
